print('olá, mundo!')
print('e nessa loucura')
print('de dizer que não te quero')
print('vou negando as aparências')
print('disfarçando as evdências')
print('mas pra que viver fingindo')
print('se eu não posso enganar meu coraçãooo')
print('eu sei que te amo!')
print('chega de mentiras, de negar o meu desejo')
print('eu te quero mais que tudo, eu preciso do seu beijo')